defaults:
  - task: run
  - regime: single_paulsson
  - benchmark: bnn_xor_function
  - policy: phoenix
  - experiment: basic
  - metrics: sparc
  - tracking: wandb
  - _self_

seed: 0

budget:
  total: 10.0

hydra:
  run:
    dir: runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${benchmark.name}_${task.name}
  sweep:
    dir: runs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
